// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.project.slice.User;

public interface UserSlice extends Ice.Object,
                                   _UserSliceOperations, _UserSliceOperationsNC
{
    public static final String ice_staticId = "::User::UserSlice";

    public static final long serialVersionUID = 511716813L;
}
