/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15-10-19 上午10:06' with Gradle 2.7
 *
 * @author Administrator, @date 15-10-19 上午10:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
