/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15-10-16 下午5:08' with Gradle 2.7
 *
 * @author Administrator, @date 15-10-16 下午5:08
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
