// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.project.api.slice.common;

public final class SimpleResponseHolder extends Ice.ObjectHolderBase<SimpleResponse>
{
    public
    SimpleResponseHolder()
    {
    }

    public
    SimpleResponseHolder(SimpleResponse value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof SimpleResponse)
        {
            value = (SimpleResponse)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return SimpleResponse.ice_staticId();
    }
}
