/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-1-12 下午5:53' with Gradle 2.7
 *
 * @author Administrator, @date 16-1-12 下午5:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
