// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.project.api.slice.user;

public class _UserSliceTie extends _UserSliceDisp implements Ice.TieBase
{
    public _UserSliceTie()
    {
    }

    public _UserSliceTie(_UserSliceOperations delegate)
    {
        _ice_delegate = delegate;
    }

    public java.lang.Object ice_delegate()
    {
        return _ice_delegate;
    }

    public void ice_delegate(java.lang.Object delegate)
    {
        _ice_delegate = (_UserSliceOperations)delegate;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        if(!(rhs instanceof _UserSliceTie))
        {
            return false;
        }

        return _ice_delegate.equals(((_UserSliceTie)rhs)._ice_delegate);
    }

    public int hashCode()
    {
        return _ice_delegate.hashCode();
    }

    public UserDto getUserInfoByPeimaryKey(long id, Ice.Current __current)
    {
        return _ice_delegate.getUserInfoByPeimaryKey(id, __current);
    }

    private _UserSliceOperations _ice_delegate;

    public static final long serialVersionUID = -396976659L;
}
