// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.project.api.slice.user;

public final class UserSliceI extends _UserSliceDisp
{
    public
    UserSliceI()
    {
    }

    public com.project.api.slice.common.BussinessResponse
    getUserInfoByPeimaryKey(long id, Ice.Current __current)
    {
        return null;
    }

    public UserDto
    updateByPeimaryKey(UserDto userDto, Ice.Current __current)
    {
        return null;
    }
}
