// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.project.api.slice.user;

public interface UserSlicePrx extends Ice.ObjectPrx
{
    public com.project.api.slice.common.BussinessResponse getUserInfoByPeimaryKey(long id);

    public com.project.api.slice.common.BussinessResponse getUserInfoByPeimaryKey(long id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, Ice.Callback __cb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, Callback_UserSlice_getUserInfoByPeimaryKey __cb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, java.util.Map<String, String> __ctx, Callback_UserSlice_getUserInfoByPeimaryKey __cb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, 
                                                         IceInternal.Functional_GenericCallback1<com.project.api.slice.common.BussinessResponse> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, 
                                                         IceInternal.Functional_GenericCallback1<com.project.api.slice.common.BussinessResponse> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, 
                                                         java.util.Map<String, String> __ctx, 
                                                         IceInternal.Functional_GenericCallback1<com.project.api.slice.common.BussinessResponse> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getUserInfoByPeimaryKey(long id, 
                                                         java.util.Map<String, String> __ctx, 
                                                         IceInternal.Functional_GenericCallback1<com.project.api.slice.common.BussinessResponse> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb);

    public com.project.api.slice.common.BussinessResponse end_getUserInfoByPeimaryKey(Ice.AsyncResult __result);

    public UserDto updateByPeimaryKey(UserDto userDto);

    public UserDto updateByPeimaryKey(UserDto userDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, Callback_UserSlice_updateByPeimaryKey __cb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, java.util.Map<String, String> __ctx, Callback_UserSlice_updateByPeimaryKey __cb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, 
                                                    IceInternal.Functional_GenericCallback1<UserDto> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, 
                                                    IceInternal.Functional_GenericCallback1<UserDto> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<UserDto> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_updateByPeimaryKey(UserDto userDto, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<UserDto> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public UserDto end_updateByPeimaryKey(Ice.AsyncResult __result);
}
